#!/usr/bin/env sh

# general space settings
yabai -m config layout                          bsp
yabai -m config top_padding                     12
yabai -m config bottom_padding                  12
yabai -m config left_padding                    12
yabai -m config right_padding                   12
yabai -m config window_gap                      12

# unmanage all windows by default
yabai -m rule --add app!="^()$" manage=off